config/routes.rb
Rails.application.routes.draw do
  get '/calls/active', to: 'calls#active', as: 'active_calls'
  resources :calls
  root 'calls#new'
  post '/calls/:id', to: 'calls#update'
  post '/callback/hangup/:id', to: 'calls#hangup_callback', as: 'hangup_callback'
end

app/models/call.rb
class Call < ActiveRecord::Base
  serialize :request_uuids, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_filter :authenticate
  skip_before_action :verify_authenticity_token, only: [:update, :hangup_callback] if :xml_request?
  before_action :set_call, only: [:show, :edit, :update, :hangup_callback, :destroy]
  before_action :set_plivo, only: [:create, :hangup]

  def index
    @calls = Call.all
  end

  def active
    @calls = Call.where(CallStatus: "in-progress")
  end

  def show
    respond_to do |format|
      format.html
      format.xml {
        r = {'Speak' => "Welcome to Charlie's demo conference.",
           'Conference' => "demo" + Time.now().strftime('%Y%m%d')}.to_xml(:root=>'Response')
        render :xml => r
      }
    end
  end

  def new
    @call = Call.new
  end

  def edit
  end

  def create
    @call = Call.new(call_params)
    respond_to do |format|
      if @call.save
        id = @call.id
        response1 = make_call(call_params['From'], id)
        response2 = make_call(call_params['To'], id)
        uuids = {'request_uuids'=> [response1[1]['request_uuid'],response2[1]['request_uuid']]}
        @call.update(uuids)
        format.html { redirect_to @call, notice: 'Call was successfully created.' }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @call['request_uuids'].include?(params[:RequestUUID]) and @call.update(update_call_params)
        r = {'Speak' => "Welcome to Charlie's demo conference.",
             'Conference' => "demo" + Time.now().strftime('%Y%m%d')}.to_xml(:root=>'Response')
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { render :show, status: :ok, location: @call }
        format.xml  { render :xml => r }
      else
        format.html { render :edit }
        format.json { render json: @call.errors, status: :unprocessable_entity }
        format.xml  { render xml:  @call.errors, status: :unprocessable_entity }
      end
    end
  end

  def hangup_callback
    respond_to do |format|
      if @call['request_uuids'].include?(params[:RequestUUID]) and @call.update(update_call_params)
        format.json { head :no_content }
        format.xml  { head :no_content }
      else
        format.json { render json: @call.errors, status: :unprocessable_entity }
        format.xml  { render xml:  @call.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url, notice: 'Call was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def authenticate
      if not xml_request?
        authenticate_or_request_with_http_basic do |name, password|
          name == "plivo" &&  password == "Charlie1234"
        end
      end
    end

    def set_call
      @call = Call.find(params[:id])
    end

    def set_plivo
      @plivo = Plivo::RestAPI.new(ENV['PLIVO_AUTH_ID'], ENV['PLIVO_AUTH_TOKEN'])
    end

    def make_call(number, id)
      call = {
        'from' => ENV['CALLERID'],
        'to' => number,
        'answer_url' => call_url(id) + ".xml",
        'hangup_url' => hangup_callback_url(id) + ".xml",
        'time_limit' => '30',
        'ring_timeout' => '15'
       }
       response = @plivo.make_call(call)
    end

    def call_params
      params.require(:call).permit(:name, :From, :To)
    end

    def update_call_params
      params.permit(:CallStatus, :CallUUID)
    end

    def xml_request?
      request.format.xml?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_form.html.erb
<%= form_for(@call) do |f| %>
  <% if @call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
      <% @call.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :From %><br>
    <%= f.text_field :From %>
  </div>
  <div class="field">
    <%= f.label :To %><br>
    <%= f.text_field :To %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calls/active.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Calls</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>From</th>
      <th>To</th>
      <th>Call Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calls.order(:created_at).each do |call| %>
      <tr>
        <td><%= call.created_at %></td>
        <td><%= call.name %> &lt<%= call.From %>&gt</td>
        <td>&lt<%= call.To %>&gt</td>
        <td><%= call.CallStatus %></td>
        <td><%= link_to 'Show', call %></td>
        <td><%= link_to 'Edit', edit_call_path(call) %></td>
        <td><%= link_to 'Destroy', call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Call', new_call_path %> |
<%= link_to 'Show all calls', calls_path %>

app/views/calls/edit.html.erb
<h1>Editing Call</h1>

<%= render 'form' %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Calls</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>From</th>
      <th>To</th>
      <th>Call Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calls.order(:created_at).each do |call| %>
      <tr>
        <td><%= call.created_at %></td>
        <td><%= call.name %> &lt<%= call.From %>&gt</td>
        <td>&lt<%= call.To %>&gt</td>
        <td><%= call.CallStatus %></td>
        <td><%= link_to 'Show', call %></td>
        <td><%= link_to 'Edit', edit_call_path(call) %></td>
        <td><%= link_to 'Destroy', call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Call', new_call_path %> |
<%= link_to 'Show all calls in progress', active_calls_path %>

app/views/calls/new.html.erb
<h1>New Call</h1>

<%= render 'form' %>

<%= link_to 'Back', calls_path %> |
<%= link_to 'Show all calls in progress', active_calls_path %> |
<%= link_to 'Show all calls', calls_path %>

app/views/calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @call.created_at %>
</p>

<p>
  <strong>From:</strong>
  <%= @call.name %> &lt<%= @call.From %>&gt
</p>

<p>
  <strong>To:</strong> &lt<%= @call.To %>&gt
</p>

<p>
  <strong>CallUUID:</strong>
  <%= @call.CallUUID %>
</p>

<p>
  <strong>Last CallStatus:</strong>
  <%= @call.CallStatus %>
</p>

<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'New Call', new_call_path %> |
<%= link_to 'Show all calls in progress', active_calls_path %> |
<%= link_to 'Show all calls', calls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plivo Click2Call</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>